version: "3"

services:
  strapi:
    build: .
    container_name: strapi-application
    restart: always
    volumes:
      - .:/srv/app
      - ./node_modules:/srv/app/node_modules
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "1337:1337"
    networks:
      - strapi

  db:
    build:
      context: .docker/postgres
    container_name: postgres-strapi
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    networks:
      - strapi

networks:
  strapi:
    driver: bridge
